name: Front Cl

on:
  push:
    branches:
      - master

jobs:
  build_Front_Server:
    runs-on: ubuntu-latest

    steps:
      - name: connect EC2 from ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/myexam
            sudo chown -R $USER:$USER .git
            sudo chmod -R 777 .git
            sudo chown -R $USER:$USER .github
            sudo chmod -R 777 .github
            git pull
            cd /home/ubuntu/myexam/front
            sudo npm install
            sudo npm run build
            sudo pkill nginx
            sudo service nginx start
            