name: Front Cl

on:
  push:
    branches:
      - master

jobs:
  build_Front_Server:
    runs-on: ubuntu-latest

    steps:
      - name: connect EC2 from ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su
            cd /home/ubuntu/myexam/front/
            git pull
            npm install
            npm run build
            systemctl stop nginx
            systemctl restart nginx
            