name: Front Cl

on:
  push:
    branches:
      - master

jobs:
  build_Front_Server:
    runs-on: ubuntu-latest

    steps:
      - name: Change permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          sudo chmod -R 777 $GITHUB_WORKSPACE

      - name: connect EC2 from ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/myexam
            sudo chown -R $USER:$USER .git
            sudo chmod -R 777 .git
            git pull
            cd /home/ubuntu/myexam/front
            sudo npm install
            sudo npm run build
            sudo pkill nginx
            sudo service nginx start
            